### ISSUE TITLE
Crash when creating a train

### ISSUE THREAD

**Issue by waj171** [Sascha-T/tele-create#2]
crash log https://mclo.gs/rYJOkYg

**Comment by KevlarBandit** [comment]
java.lang.RuntimeException: Mixin transformation of com.simibubi.create.content.contraptions.components.structureMovement.ContraptionCollider failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.simibubi.create.content.contraptions.components.structureMovement.ContraptionHandler.tick(ContraptionHandler.java:57)
	at com.simibubi.create.events.CommonEvents.onWorldTick(CommonEvents.java:153)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:108)
	at net.minecraft.server.world.ServerWorld.handler$cge000$endWorldTick(ServerWorld:9166)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:374)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:907)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:97)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273)
	at java.lang.Thread.run(Thread.java:833)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector getEntitiesOfClass(Lnet/minecraft/class_1937;Ljava/lang/Class;Lnet/minecraft/class_238;Ljava/util/function/Predicate;)Ljava/util/List; in telecreate.mixins.json:ContraptionColliderMixin from mod telecreate failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap telecreate-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 18 more


This also occurs if a train is created without the mod installed then the world is joined with the mod installed.

It *also* occurs whenever *any* contraption is created.

**Comment by jakebussell** [comment]
[crash-2022-09-05_22.45.26-server.txt](https://github.com/Sascha-T/tele-create/files/9492092/crash-2022-09-05_22.45.26-server.txt)
Similar issue to above, booted a local server already with Create  installed, it finished loading but then crashed.

**Comment by ArmouredDrood** [comment]
same issue. Immersive portals work fine, track connection successfully forms across portal. 

When assembling train to drive through portal, specifically at the final stage of assembly when forming the train in the train station, crash. (I have not tested other contraptions, only trains)

crash report here: https://pastebin.com/PRnkYxyD

latest log here: https://pastebin.com/A6Phi3TB

Very excited for this to work, thank you for your hard work.

**Comment by DarianLStephens** [comment]
Maybe it's due to the dev redirect target remap thing? It's a change to that mixin, and was only merged a few months after the initial curseforge release. Without compiling a new build, we don't have that commit.

**Comment by galacticlemonade** [comment]
I just found this mod and so I have been trying to fix it and port it to 1.19.2, but it seems like the issue is `Critical injection failure: Redirector getEntitiesOfClass(Lnet/minecraft/class_1937;Ljava/lang/Class;Lnet/minecraft/class_238;Ljava/util/function/Predicate;)Ljava/util/List; in telecreate.mixins.json:ContraptionColliderMixin from mod telecreate failed injection check,` but I can't seem to find a fix for why it doesn't have a target.

**Comment by DarianLStephens** [comment]
It seems that something's changed in the contraption collider on Create's end, and telecreate's trying to mixin in the wrong place now.
If that gets changed, the mod might start working properly again.

**Comment by KevlarBandit** [comment]
I've got a working version already ported to 1.19.2 with several additional fixes and have had permission from Sascha to distribute it, I'll be doing so in the next couple of days. I'm just trying to do a minor amount of additional bug-testing first.

**Comment by KevlarBandit** [comment]
https://www.dropbox.com/s/chay7nhip54ywge/immersive_trains-1.0.1.jar?dl=0

Here is a link to a fabric 1.19.2 version. I'll get a github link setup in the near future. Testing would be appreciated. So far, the big thing I haven't fixed is the rendering and I don't have any idea where to start on that.

I also, at least for now, made the trains portion of create use the create dimension crossing. That means you will get a loading screen. It also means that you won't get teleported to weird places when you go through a portal. You can use immersive portals to go to dimensions other than the nether. If you make linked portals in the overworld, they have to be in the same orientation or the train won't connect. Train scheduling does work even across multiple dimensions. Horizontal portals don't work for trains and I have no intention of even trying to make them work.

Create contraptions won't go through portals which means no dupe glitches.  I want to fix it so that minecart contraptions can go through but that requires a non-trivial amount of work to identify where the contraption is getting destroyed and to properly move it across dimensions without having it turn into real blocks. I'm tempted to see if I can use some of the create train code to make create contraptions work cross dimensions, like have a piston in one dimension that can poke through a portal into another and do stuff there. I imagine that would be a nightmare to make work properly.

If a contraption becomes real blocks while crossing a portal, the portal gets destroyed.

Some of these aren't changes from the 1.18 version but I figured it would be good to state the current state of the mod as far as I am aware. Once I get some more stability testing done on a server (should be able to determine by the end of this week, other people testing would be great!) I will put it up on modrinth and maybe curseforge. If I can work something out I might just push it as an update to telecreate. Until that time, I went ahead and changed the name to make it more distinct.

**Comment by DarianLStephens** [comment]
A couple little bugs:
When breaking a curved track coming out of a portal, it doesn't visually break until you break the actual portal-connecting rail block.
I also had a crash when trying to ride my train backwards through a portal, plus utter LOADS of errors, probably one per frame trying to render through the portal:
https://pastebin.com/4EcQNvk5

**Comment by KevlarBandit** [comment]
Make sure that isn't a create bug with vanilla nether portals. I wasn't getting errors last time I checked... I'll look into it later. It is late and I need to go to sleep. I haven't had it crash when going backwards through a portal...

Also, what version of immersive portals and create are you using?

**Comment by KevlarBandit** [comment]
Ok, took a quick look at the crash log. Looks like immersive trains didn't actually get included in the log other than as a running mod. The crash appears to be just an immersive portals issue.

Would you mind taking a screenshot of your setup and seeing if you can replicate the crash?

**Comment by DarianLStephens** [comment]
I was testing some more, unrelated to the crash, and this just happened:
![2023-01-30_22 30 49](https://user-images.githubusercontent.com/15375876/215465533-a872cbcc-cb11-4492-8cf8-973199f9c273.png)
I didn't change anything about the track, besides resizing the portal and replacing the portal track. Maybe something to do with me breaking the obsidian directly and not the track first, or that I placed the track through the portal (That is, reaching through the portal from the other side to place the track?)

**Comment by DarianLStephens** [comment]
The crash was reproducible, and seems to only happen when using the vanilla loading screen, which also only happens when I'm actually seated on the contraption. Riding free appears to mostly work, just going straight through the portal as intended by IP and generally staying on top of the contraption.

EDIT: 
Create version is `create-fabric-0.5.0g-791+1.19.2`
Immersive Portals version is `immersive-portals-2.3.1-mc1.19.2-fabric`

**Comment by KevlarBandit** [comment]
Ok, I lied. I went ahead and took a look at it.

I can't replicate the crash and I see the log spam you are talking about. I believe that is vanilla create log spam. I will do further testing later.

Any chance you can pack up the world into a zip so I can try it?

Ah, it looks like you are using an older version of create than I am. Try `create-fabric-0.5.0g-796+1.19.2` If upgrading doesn't work, send me the world if you can. I'll take a look later.

And yes, when seated, you are teleported using creates method of teleportation. When standing immersive trains doesn't get involved at all with your player. I specifically do a check for seated characters on the immersive portals side and don't have it teleport them. Before I did that I was having problems with getting teleported 50+ blocks away on going through the portal.

**Comment by DarianLStephens** [comment]
I literally just tested that version when I realized it was outdated, and it unfortunately still crashed when going through seated.
As for uploading the world, I'd like to, but even when compressed it's bigger than Github is happy with (30MB vs Git's limit of 25MB, frustratingly.)

**Comment by KevlarBandit** [comment]
Any chance you can upload to an alternative site?

Also, watch out, there is an issue with controlling the train while not seated. If you go too slow through a portal you can fall down into the portal block and get stuck in a state where you are controlling a train that no longer exists so you can't stop controlling it. Reloading the world seems to fix it. Not sure how that would play on a dedicated server.

I likely need to add some logic to check if the player is currently controlling a train when they go through a portal and stop it or redirect their control in certain cases.

**Comment by DarianLStephens** [comment]
That's... a new one. I just loaded back in to the world, and I'm now at spawn?
![2023-01-30_22 48 47](https://user-images.githubusercontent.com/15375876/215469482-46470545-7f92-42aa-8c2a-e1b3f7e6bf48.png)
Yeah, it's the same world!
![2023-01-30_22 50 40](https://user-images.githubusercontent.com/15375876/215469494-106749b4-4e21-4cf3-9a73-ebf05ddedaa0.png)

**Comment by DarianLStephens** [comment]
With rendering, it looks mostly like the contraption just isn't updating properly anymore? Maybe because of the perceived distance? If you go through a portal and back in, it will render pretty close to normally, but won't move again until you go back through.

**Comment by KevlarBandit** [comment]
I haven't had that before. Could be a chunk corruption bug. Those don't usually send you back to world spawn though.

I see that it says you are running many mods. Any chance I can get a list of those mods? It is *possible* there is an incompatibility with one of the other mods. Especially if you have addons for create. (Though I'm pretty sure I'm already running all of the create fabric addons, I haven't checked in the last two-three weeks.)

**Comment by KevlarBandit** [comment]
Yes, that rendering issue is a persistent one. I'm not sure how to fix it. (Maybe I can force a reload on a slight delay after a train goes through a portal?) Telecreate has the same problem.

**Comment by DarianLStephens** [comment]
It's not as many mods as you might think:
![image](https://user-images.githubusercontent.com/15375876/215471412-16ebd619-96e6-497b-953f-9ed0edc1c8cd.png)

With rendering, maybe you can adjust whatever distance-detection it uses to account for portals? If that's the problem, of course.

**Comment by KevlarBandit** [comment]
Hmm, most of those mods I have in the pack I'm testing with already... (Watch out, mousewheelie is annoying in creative!)

I think I will need the world download and see if I can replicate. If that doesn't work, I have no idea.

At least for now, the train scheduling works well. And to my knowledge, all of the fixes I would apply to immersive trains would not be breaking fixes so it is probably playable, at least if you just use the train scheduling. There also shouldn't be a concern with future updates to it being incompatible.

Ok, I'm actually going to sleep now.

**Comment by DarianLStephens** [comment]
Ah, I've been well acquainted with Mousewheelie's creative problem. I'm so used to scrolling just... anywhere, so having to move explicitly to the scrollbar is a headache.

I'd been considering turning on IP's option to light a vanilla portal when crouching, just so Create's trains can work, but it'll be great to not need that workaround for this.

Here's the world off Google Drive:
https://drive.google.com/file/d/121z07cNzlDonDRzol7yD1SyYmB9658iN/view?usp=share_link

Thanks for doing this, goodnight.

**Comment by KevlarBandit** [comment]
So I downloaded it and couldn't get a crash on my instance..

Send me an email so I can send you a link to an instance that you can try out. It has an ip for a server running the pack so I want to avoid handing it out publicly.

winder.chassis0i@icloud.com
